## Simple bond pricing functions

#' Simplified bond price calculation
#'
#' Price of a bond with annual coupon, computed
#' on coupon payment date
#' \deqn{
#' P = \sum_{i=1}^n \frac{c}{(1+y)^i} + \frac{1}{(1+r)^n}
#' }
#'
#' @title Bond price
#' @param coupon (real) coupon rate (.05: 5\%)
#' @param n (integer) number of years to expiry
#' @param yield (real) yield to maturity
#' @return price of $1 nominal
#' @examples
#' p <- SimpleBondPrice(.05, 10, .05)
#' @export

SimpleBondPrice <- function(coupon, n, yield) {
  100*sum(sapply(1:n, function(i) ifelse(i<n, coupon/(1 + yield)^i, (1+coupon)/(1+yield)^n)))
}

#' Simplified bond variation calculation
#'
#' Derivative of bond price with respect to yield
#' \deqn{ v = \frac{\partial P}{\partial y}}

#' @title Bond variation
#' @param coupon (real) coupon rate (.05: 5\%)
#' @param n (integer) number of years to expiry
#' @param yield (real) yield to maturity
#' @return derivative of price with respect to yield
#' @examples
#' p <- SimpleVariation(.05, 10, .05)
#' @export

SimpleVariation <- function(coupon, n, yield) {
  -100*sum(sapply(1:n, function(i) ifelse(i<n, i*coupon/(1 + yield)^(i+1), 
                                         n*(1+coupon)/(1+yield)^(n+1))))
}

#' Simplified bond sensitivity calculation
#'
#' Bond sensitivity with respect to yield, ie.
#' \deqn{ s = -\frac{frac{\partial P}{\partial y}}{P} }
#' 
#'
#' @title Bond sensitivity
#' @param coupon (real) coupon rate (.05: 5\%)
#' @param n (integer) number of years to expiry
#' @param yield (real) yield to maturity
#' @return derivative of price with respect to yield
#' @examples
#' s <- SimpleSensitivity(.05, 10, .05)
#' @export

SimpleSensitivity <- function(coupon, n, yield) {
  -SimpleVariation(coupon,n,yield)/SimpleBondPrice(coupon, n, yield)
}

#' Simplified bond duration calculation
#'
#' Modified duration of a bond price. It is the weighted
#' maturity, where the weights are the present value of
#' the cash flow paid at each date. Let \eqn{F_i} be the
#' cash flow paid at time \eqn{i}. Duration is defined as
#' \deqn{ d = \sum_{i=1}^n \frac{F_i (1+y)^{-i}}{P}}

#' @title Bond duration
#' @param coupon (real) coupon rate (.05: 5\%)
#' @param n (integer) number of years to expiry
#' @param yield (real) yield to maturity
#' @return derivative of price with respect to yield
#' @examples
#' d <- SimpleDuration(.05, 10, .05)
#' @export

SimpleDuration <- function(coupon, n, yield) {
  100*sum(sapply(1:n, function(i) ifelse(i<n, i*coupon/(1 + yield)^i, 
  n*(1+coupon)/(1+yield)^n)))/SimpleBondPrice(coupon,n,yield)
}

#' Bond Definition 
#'
#' This function constructs a data structure that
#' describes the cash flow schedule of a bond.

#' @title Bond cash flow generator
#' @param id (string) the identifier of the bond
#' @param dtIssue (date) bond issue date
#' @param dtMaturity (date) bond maturity date
#' @param couponRate (real) coupon rate, in decimal form
#' @param nominal (real) nominal amount
#' @param frequency (string) 'A' for annual, 'S' for semi-annual.
#' @return a list with the following elements:
#' \describe{
#' \item{id}{the bond identifier}
#' \item{cf}{vector of cash flows}
#' \item{dt}{vector of payment dates for each cash flow}
#' \item{freq}{frequency ("a" or "s")}
#' \item{coupon}{coupon rate}
#' \item{nominal}{nominal amount}
#' }
#'
#' @examples
#' b374 <- Bond('374', myDate('01/01/2000'),
#'              myDate('04/01/2019'), .0375, 100, 'a')
#' @export

Bond <- function(id, dtIssue, dtMaturity, couponRate, nominal, frequency) {
  
  freq <- switch(toupper(frequency),
  A = 1, 
  S = 2)

  cf <- vector()
  dt <- vector()
  d <- dtMaturity
  i <- 1
  cf[i] <- nominal*(couponRate/freq + 1)
  dt[i] <- d
  d <- d - 365/freq
  
  while(d>dtIssue) {
    i <- i+1
    cf[i] <- nominal*couponRate/freq 
    dt[i] <- d
    d <- d - 365/freq 
  }
    
  res <- list(id=id, cf=cf, dt=as.Date(dt, origin=myDate('01jan1970')), freq=freq, coupon=couponRate, nominal=nominal)  
  res 
}

#' Bond accrued interest
#'
#' This function computes the accrued interest on a bond by the formula
#' \deqn{
#' ac = c N \frac{m}{365}
#' }
#'
#' with
#' \describe{
#' \item{\eqn{c}}{coupon rate}
#' \item{\eqn{N}}{nominal amount}
#' \item{\eqn{m}}{actual number of days since last coupon payment}
#' }
#' @param bond data structure generated by \code{Bond}
#' @param dtSettlement settlement date
#' @return the accrued interest
#'
#' @examples
#' b374 <- Bond('374', myDate('01/01/2000'),
#'              myDate('04/01/2019'), .0375, 100, 'a')
#' a <- BondAC(b374, myDate('03/01/2012'))
#' @export

BondAC <- function(bond, dtSettlement){
  dt <- dtSettlement
  dd <- as.numeric(min(dt - bond$dt[bond$dt <= dt]))
  bond$nominal*bond$coupon*dd/365
}

#' Bond PV01
#'
#' This function computes the PV01 (present value of one basis point) of a bond by the formula
#' \deqn{
#' PV01 = \frac{1}{10000} \frac{\partial P(y)}{\partial y}
#' }
#' given the bond price or yield. 
#'
#' with
#' \describe{
#' \item{\eqn{P(y)}}{bond price, function of yield}
#' }
#' @param bond data structure generated by \code{Bond}
#' @param dtSettlement settlement date
#' @param yield (optional) bond yield
#' @param price (optional) bond price
#' @return PV01
#'
#' @examples
#' b374 <- Bond('374', myDate('01/01/2000'),
#'              myDate('04/01/2019'), .0375, 100, 'a')
#' pv01 <- BondPV01(b374, myDate('03/01/2012'), yield=.04)
#' @export

BondPV01 <- function(bond, dtSettlement, yield, price=NULL) {
  dr <- .01/100 #1 bp
  if(is.null(price))
    price = BondYield2Price(bond, dtSettlement, yield)
  (price - BondYield2Price(bond, dtSettlement, yield-dr)) / dr
}


#' Bond convexity
#'
#' This function computes the convexity of a bond by the formula
#' \deqn{
#' Cx = \frac{\partial^2 P(y)}{\partial y^2}
#' }
#' given the bond price or yield. 
#'
#' with
#' \describe{
#' \item{\eqn{P(y)}}{bond price, function of yield}
#' }
#' @param bond data structure generated by \code{Bond}
#' @param dtSettlement settlement date
#' @param yield (optional) bond yield
#' @param price (optional) bond price
#' @return Bond convexity
#'
#' @examples
#' b374 <- Bond('374', myDate('01/01/2000'),
#'              myDate('04/01/2019'), .0375, 100, 'a')
#' Cvx <- BondCvx(b374, myDate('03/01/2012'), yield=.04)
#' @export

BondCvx <- function(bond, dtSettlement, yield, price=NULL) {
  dr <- 50 * .01/100 # 50 bp
  if(is.null(price))
    price = BondYield2Price(bond, dtSettlement, yield)
  P1 = BondYield2Price(bond, dtSettlement, yield-dr)
  P2 = BondYield2Price(bond, dtSettlement, yield+dr)

((P1+P2)/2 - price)/(dr^2)
}

#' Bond price from yield
#'
#' This function computes the bond (dirty) price, given its yield, by the formula
#' \deqn{
#' P = \sum_{i=1}^n F_i (1+y)^{-\frac{d_i - d_0}{365}}
#' }
#' with:
#' \describe{
#' \item{\eqn{F_i}}{Cash flow paid at date \eqn{d_i}}
#' \item{\eqn{d_i}}{Cash flow date, measured in days}
#' \item{\eqn{d_0}}{settlement date}
#' }

#' @param bond data structure generated by \code{Bond}
#' @param dtSettlement settlement date
#' @param yield bond yield
#' @return dirty price
#'
#' @examples
#' b374 <- Bond('374', myDate('01/01/2000'),
#'              myDate('04/01/2019'), .0375, 100, 'a')
#' p <- BondYield2Price(b374, myDate('03/01/2012'), yield=.04)
#' @export
 
BondYield2Price <- function(bond, dtSettlement, yield) {
  price <- 0
  dt <- as.numeric(dtSettlement)
  for(i in seq_len(length(bond$dt))) {
    if(bond$dt[i]>dt) {
    TimeFraction = bond$freq*as.numeric(bond$dt[i]-dt)/365
    price <- price + bond$cf[i]/((1+yield/bond$freq)^TimeFraction)
    }
  }
  price
}

#' Bond yield from price
#'
#' This function computes the bond yield, given its dirty price by solving for \eqn{y} the equation:
#' \deqn{
#' P = \sum_{i=1}^n F_i (1+y)^{-\frac{d_i - d_0}{365}}
#' }
#' with:
#' \describe{
#' \item{\eqn{F_i}}{Cash flow paid at date \eqn{d_i}}
#' \item{\eqn{y}}{yield}
#' \item{\eqn{d_i}}{Cash flow date, measured in days}
#' \item{\eqn{d_0}}{settlement date}
#' }

#' @param bond data structure generated by \code{Bond}
#' @param dtSettlement settlement date
#' @param price bond dirty price
#' @return bond yield
#'
#' @examples
#' b374 <- Bond('374', myDate('01/01/2000'),
#'              myDate('04/01/2019'), .0375, 100, 'a')
#' y <- Price2BondYield(b374, myDate('03/01/2012'),
#'      price=101)
#' @export

Price2BondYield <- function(bond, dtSettlement, price) {

  errP <- function(y) {price - BondYield2Price(bond, dtSettlement, y)}
  
  r <- uniroot(errP, c(.001, .3))
  r$root
}

